service: my-fastapi-app

provider:
  name: aws
  runtime: python3.9
  region: us-east-1

functions:
  api:
    handler: main.handler
    events:
      - httpApi:
          path: /
          method: GET
      - httpApi:
          path: /hello/{proxy+}
          method: GET

plugins:
  - serverless-offline